create database QLGARA
GO
set dateformat dmy
use QLGARA
 CREATE TABLE PHUTUNG
 (
	MAPT CHAR (10) PRIMARY KEY,
	TenPT VARCHAR (50),
	SL INT,
	GIA FLOAT,
	DONVI VARCHAR(50)
 )

 CREATE TABLE PHIEUSUACHUA
 (
	MaPSC CHAR (10) PRIMARY KEY,
	MaPT CHAR (10) ,
	MaPTN CHAR (10),
	SL_SC INT ,
	NgaySC SMALLDATETIME,
	NOIDUNG VARCHAR (100),
	TenPT varchar (50),
	TienCong FLOAT,
	ThanhTien float,
 )
 ALTER TABLE PHIEUSUACHUA ADD CONSTRAINT PSC_PT FOREIGN KEY (MAPT) REFERENCES PHUTUNG(MAPT)
 ALTER TABLE PHIEUSUACHUA ADD CONSTRAINT PSC_PTN FOREIGN KEY (MAPTN) REFERENCES PHIEUTIEPNHAN(MAPTN)


 CREATE TABLE PHIEUTHUTIEN
 (
	MAPTT CHAR(10) ,
	MAXE CHAR(10) ,
	MAPSC CHAR (10),
	TIENTHU FLOAT,
	NGAYTHU SMALLDATETIME,
	CONSTRAINT PK_PTT_HX PRIMARY KEY (MAPTT, MAXE)
 )
 DROP TABLE PHIEUTHUTIEN
ALTER TABLE PHIEUTHUTIEN ADD CONSTRAINT PTT_PSC FOREIGN KEY (MAPSC) REFERENCES PHIEUSUACHUA(MAPSC)
ALTER TABLE PHIEUTHUTIEN ADD CONSTRAINT PTT_HX FOREIGN KEY (MAXE) REFERENCES HIEUXE(MAXE)


 CREATE TABLE TT_XE
 (
	MATTXE CHAR (10) PRIMARY KEY,
	MAKH CHAR (10) ,
	MAXE CHAR (10) ,
	BIENSO VARCHAR (50),
 )
ALTER TABLE TT_XE ADD CONSTRAINT TTXE_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE TT_XE ADD CONSTRAINT TTXE_HX FOREIGN KEY (MAXE) REFERENCES HIEUXE(MAXE)

 DROP TABLE TT_XE

 CREATE TABLE HIEUXE
 (
	MAXE CHAR (10) PRIMARY KEY,
	TENXE VARCHAR (50),
 )
  CREATE TABLE PHIEUTIEPNHAN
  (
	MAPTN CHAR (10) PRIMARY KEY,
	MAXE CHAR (10) ,
	MAKH CHAR (10),
	NGAYTIEPNHAN SMALLDATETIME,
  )
ALTER TABLE PHIEUTIEPNHAN ADD CONSTRAINT PTN_HX FOREIGN KEY (MAXE) REFERENCES HIEUXE(MAXE)
ALTER TABLE PHIEUTIEPNHAN ADD CONSTRAINT PTN_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

CREATE TABLE LGIN
(
	USERID INT IDENTITY NOT NULL,
	USERNAME VARCHAR(50),
	PASSWORD_PW VARCHAR(50)
	CONSTRAINT PK_USERID PRIMARY KEY (USERID)
)


CREATE TABLE NHAPPHATSINH
(
	MAPHIEUP CHAR(10),
	MAPT CHAR(10),
	NGAYPS SMALLDATETIME,
	SOLUONGPS INT,
	DONGIAPS INT,
	TONGTIENPS INT
	CONSTRAINT PK_MAPHIEUP PRIMARY KEY (MAPHIEUP)

)

-- KHÓA NGOẠI
ALTER TABLE NHAPPHATSINH ADD CONSTRAINT FK1_MAPHIEUPS FOREIGN KEY(MAPT) REFERENCES PHUTUNG(MAPT)
ALTER TABLE NHAPPHATSINH DROP CONSTRAINT FK1_MAPHIEUPS

CREATE TABLE KHACHHANG
(
	MAKH CHAR(10),
	TENKH VARCHAR(50),
	SDT CHAR(10),
	NGAYSINH SMALLDATETIME,
	DIACHI VARCHAR(50),
	TIENNO INT
	CONSTRAINT PK_MAKH PRIMARY KEY (MAKH)
)
DROP TABLE KHACHHANG

CREATE TABLE BAOCAOTON
(
	THANG INT,
	MAPT CHAR(10),
	TONDAU INT,
	PHATSINH INT,
	TONCUOI INT
	CONSTRAINT PK_THANG PRIMARY KEY (THANG)
)
-- KHÓA NGOẠI
ALTER TABLE NHAPPHATSINH ADD CONSTRAINT FK1_BAOCAOTON FOREIGN KEY (MAPT) REFERENCES PHUTUNG(MAPT)
ALTER TABLE NHAPPHATSINH DROP CONSTRAINT FK1_BAOCAOTON
